[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "dataset_similarity"
version = "0.1.0"
authors = [
  { name = "Phil Swatton", email = "pswatton@turing.ac.uk" },
  { name = "Jack Dymond", email = "j.dymond@turing.ac.uk" },
  { name = "Colin Laganier", email = "claganier@turing.ac.uk" },
]
description = "Repo for ARC project on dataset similarity measures."
readme = "README.md"
requires-python = ">=3.10,<3.13"
classifiers = [
  "Development Status :: 1 - Planning",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Scientific/Engineering",
  "Typing :: Typed",
]
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "pyyaml>=6.0",
    "safetensors>=0.4.0",
    "torch==2.10.*",
    "torchvision",
    "markupsafe==3.0.*",  # This is needed for torch to work
    "transformers>=5.4.0",
    "pyaml>=26.2.1",
    "scikit-learn>=1.7.2",
    "pandas>=2.3.3",
    "otdd",
    "torchtext>0.14.1,<=0.18.0", # not actually required by us but by OTDD. Our torch setup leads to the wrong version being installed if we do not control version + source here
]

[dependency-groups]
dev = [
    "pre-commit",
    "pytest>=6",
    "pytest-cov>=3",
]

[tool.uv.sources]
otdd = { git = "https://github.com/microsoft/otdd" }
torch = [
  { index = "pypi", marker = "platform_machine != 'aarch64'"},
  { index = "pytorch-cu126", marker = "platform_machine == 'aarch64'"},
]
torchvision = [
  { index = "pypi", marker = "platform_machine != 'aarch64'"},
  { index = "pytorch-cu126", marker = "platform_machine == 'aarch64'"},
]
torchtext = [
  { index = "pypi", marker = "platform_machine != 'aarch64'"},
  { index = "pytorch-cu126", marker = "platform_machine == 'aarch64'"},
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"

[project.urls]
Homepage = "https://github.com/alan-turing-institute/ARC-Dataset-Similarity"
"Bug Tracker" = "https://github.com/alan-turing-institute/ARC-Dataset-Similarity/issues"
Discussions = "https://github.com/alan-turing-institute/ARC-Dataset-Similarity/discussions"
Changelog = "https://github.com/alan-turing-institute/ARC-Dataset-Similarity/releases"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
filterwarnings = [
  "error",
]
log_cli_level = "INFO"
testpaths = [
  "tests",
]

[tool.coverage]
run.source = ["dataset_similarity"]
port.exclude_lines = [
  'pragma: no cover',
  '\.\.\.',
  'if typing.TYPE_CHECKING:',
]

[tool.mypy]
files = ["src", "tests"]
python_version = "3.10"
show_error_codes = true
warn_unreachable = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true
strict = true
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]

[[tool.mypy.overrides]]
module = "dataset_similarity.*"
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.ruff]
src = ["src"]
exclude = []
line-length = 88  # how long you want lines to be

[tool.ruff.format]
docstring-code-format = true  # code snippets in docstrings will be formatted

[tool.ruff.lint]
select = [
  "E", "F", "W", # flake8
  "B",           # flake8-bugbear
  "I",           # isort
  "ARG",         # flake8-unused-arguments
  "C4",          # flake8-comprehensions
  "EM",          # flake8-errmsg
  "ICN",         # flake8-import-conventions
  "ISC",         # flake8-implicit-str-concat
  "G",           # flake8-logging-format
  "PGH",         # pygrep-hooks
  "PIE",         # flake8-pie
  "PL",          # pylint
  "PT",          # flake8-pytest-style
  "RET",         # flake8-return
  "RUF",         # Ruff-specific
  "SIM",         # flake8-simplify
  "UP",          # pyupgrade
  "YTT",         # flake8-2020
  "EXE",         # flake8-executable
]
ignore = [
  "PLR",    # Design related pylint codes
  "ISC001", # Conflicts with formatter
]
unfixable = [
  "F401",   # Would remove unused imports
  "F841",   # Would remove unused variables
]
flake8-unused-arguments.ignore-variadic-names = true  # allow unused *args/**kwargsisort.required-imports = ["from __future__ import annotations"]
