data_config: domainnet_clipart_1000

# these are passed directly to:
# transformers.AutoModelForImageClassification.from_pretrained
model_args:
  pretrained_model_name_or_path: "microsoft/resnet-50"
  device_map: cpu

training_args:
  num_train_epochs: 10
  per_device_train_batch_size: 32
  learning_rate: 0.001
