# The following is equivalent to F-OTCE
metric: otce_distance
kwargs:
    use_wasserstein: False
    use_otdd: False
    use_flash_sinkhorn: False
    metric: sqeuclidean
    method: sinkhorn
    reg: 0.1
    debias: False  # Coupling only so debiasing set to False in any case
