# The following is equivalent to F-OTCE
metric: otce_distance
kwargs:
    use_wasserstein: False
    use_otdd: False
    use_sinkhorn: True
    use_flash_sinkhorn: False # passed to ot_sinkhorn
    device: cuda
    debias: False # no point debiasing as coupling only is used
    blur: 0.05
    scaling: 0.9
    p: 2
